[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "integrate"
version = "0.2.2"
dependencies = [
    "numpy>=1.26.4",
    "matplotlib>=3.8.3", 
    "h5py>=3.10.0",
    "scipy",
    "psutil",
    "tqdm>=4.66.2",
    "jupyter>=1.0.0",
    "jupytext",
    "pandas",
    "pyvista",
    "ga-aem-forward-win; platform_system == 'Windows'",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
]

[project.scripts]
integrate_timing = "integrate.examples.integrate_timing:main"
integrate_rejection = "integrate.integrate_cli:main"

[tool.setuptools]
packages = ["integrate"]
